doc-warnings : true
test-warnings : false
strictness: medium
max-line-length : 80
autodetect: true
ignore-paths:
   - docs
   - lightpath/__init__.py
ignore-patterns:
    - versioneer.py
    - lightpath/_version.py
python-targets:
    - 3
pylint:
    disable:
        - protected-access
