version: ~> 1.0

env:
  global:
    - OFFICIAL_REPO="pcdshub/lightpath"
    - secure: "TsbDiFJe8vTjJCZJowjVkWFpBd2w+gCr+56F4TUlhLFN9aZvaUwyEEiWx3KWzFqYndUTLZsbZNSmekE63w4ZUGKhNa/DALxKo2Pt5esKfIWKoiiTM8YI39x3luiS8eiJ3t/XrC5R28MnH5dd8rCl+RaUkT/nJQcjz3YLl4bjbSnbr18HhsodmydW1zvFX8Jyxv42j8wyc2P0dZkX+SuaEZ0lsVH4QCK0seIf8f4uE6t/C1VuFWBPS+q5t3y2FwGQpH3CpAI5MEyHsnyCyQaP4khVQJRnjnSQ7M4oqy0t3WQYwPXSvwxZdswGmFLFru31GDpYVYcOFYtwOvF5NBr9Pg2yViLZOEY9niUgz0MEe6W+H2SDyGyZcRcSLciiK43jU0tqNEXOo/AN9FSup9FabmaBihxMbKYuKASsRW5/MelRJ+u6q2hun2+XUXd6VxRdTuIsqStR7q237ZTyTyiixH3zaeIpNRffPAg2u1SyLmLMVUkF+dsPtaQgWudBIjvSdSJFD3ZAWMnhC1xz9S4lLZqvHwWWp8BpCDkm8SsQkADvA6Y9j62shOtozv89qnSwaJB2MKNASireoOROCMxRSLB1N9BTDjTcQE0qC8U7JI/gRep+hVLannF8LpLksyrUn25jFE2diNvzvxbjYN6RLSuUiDhHieDFT7iKM1DUyL0=" 

    - DOCTR_VERSIONS_MENU="1"
    - DOCS_REQUIREMENTS="dev-requirements.txt"
    - PYTHON_LINT_OPTIONS="lightpath"

    - CONDA_PACKAGE="lightpath"
    - CONDA_RECIPE_FOLDER="conda-recipe"
    - CONDA_EXTRAS="pip"
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    - PIP_EXTRAS="PyQt5"

jobs:
  allow_failures:
    - name: "Python 3.8 - PIP"
    - name: "Python 3.9"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
