language: python
sudo: false
env:
  global:
    - OFFICIAL_REPO="slaclab/lightpath"
    - secure: "tV+zuW0Wqt4pruoWfHAW3sNHSGXqPQjmhYf0qpxPvFyMFISP8tBxSnVlcPyQN0ILBdbkhTOXBUWuaRSYOBJdAleCPxcdR5A0dIjUsqVz7+0f2ec3ucDCi5Ge+xaZy6LzCI0ZJE0o/SvdOeSpLimj4+jKhEQUTqGphNNVXVct0R9sSP7wZopGlKs/6BQ3gbkdGGX7t5n0edUMrxZ9AfjA8eYcOQ8CIiKJ7viUGT7FG+bk8CyNrwcVy1r6Emh2gIPdgsCIspHsUrLYK4ll/lzrnkNR690Qqlo2HDcvlCpPUStJAtfMh8JDmZ/ECl8uT/A8O7x6PEE1+wfq4s6gO7e2xEgdscVnm3EgQE0/ixxf0ahX61BGZcNo2bWy5R027SeMGn0WEmvRL0jkHFrU4i7sglyiS/aFLIRg2zmq2zXovE7tmtBwxbKuA7K3RkpwOF3XDoRDh0sGGNf2XvzCVkdQds/ZSW4Ygw8PcQ7YwjEW9LQwponeFY/5Y1eZLFoz+i3UE7xbMFbfnmntXjvKCbpLZgbLC3u86jTMEx+F2LC/4RiGxGtNAI+igr+No5LdWiVo4ct2orloNvtXbB1xoBLG4T3z5fklhyN4wi6AjrapPqDP4dpNxMxw1pi6+yzBi1aHOi/trKJvTvfTqpXN9E3FPy68SjJCGDgyoK9SmJVJh4k="

matrix:
  include:
      - python: 3.5
      - python: 3.6
        env: BUILD_DOCS=1

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  - conda config --append channels pcds-tag
  - conda config --append channels pydm-dev
  - conda config --append channels lightsource2-tag
  - conda config --append channels gsecars
  - conda config --append channels conda-forge
  # Useful for debugging any issues with conda
  - conda info -a
  - conda build -q conda-recipe --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"
  # Create test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION lightpath --file dev-requirements.txt
  - source activate test-environment

before_script:
    #Take from docs.travis-ci.com/user/gui-and-headless-browsers
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - coverage run run_tests.py
  - coverage report -m
  - set -e
  # Build docs.
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY" && $BUILD_DOCS ]]; then
      #Install doctr from a custom branch until
      #https://github.com/drdoctr/doctr/pull/190 is merged.
      pip uninstall -y doctr
      pip install git+https://github.com/danielballan/doctr@other-master 
      pushd docs
      make html
      popd
      # Publish docs.
      doctr deploy --deploy-repo lcls-pcds/skywalker-docs --deploy-branch-name master lightpath
    fi

after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' && $CONDA_UPLOAD_TOKEN_TAG != '' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' && $CONDA_UPLOAD_TOKEN_DEV != '' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
