version: ~> 1.0

env:
  global:
    - OFFICIAL_REPO="pcdshub/lightpath"
    - secure: "O3LwEwyXhMz8FPMB3/9EsRvEZkMrqnOeywpGOxBZyLYpuoVBslphTz07VqXmtrI7J7PT6klXK/dCZlRDsNConx8P0D1LVDqFCWO8ftDyAOAaXYSjevlGhZ75BmR+eksKuoPpY4Qq0+KWX6MxU6W/esQQ2WsTFWr1u2ClQavmGvq2zSK2QeA1i5wTbpmEhRc+6HWGTgLx4lNrdq2z9Y14LnKluFeM926uGoAAgp1PCyXzETiEeGt1uB/2wNcxRE9bhvnFEAFVT6QBzRdU4uFJ4TR4Xad/RBuRNyHCXtJMaCTmXdpLSObe6r1oXjGjrR7Ycqco88lAnaU77Co0jaOCGZyAp+PTHSSfYxVSJq/k9hBySjZvXXZgUE0VwXF3xcZshqH9dcJFPvwfCoT/Vqr2pRBzc/+pYc35UAnLWnIX8u+jgySVwr+zmycY4AjWq5wyJznXCiNLpoSAufv5Q4qyMrPPkKbgXNJhyzODcgPzB+gDoiXiYIYjDGn7MYB0zsm6/a2X/bRmTb+oja/NLGnePXvs71K1/1oydYE+IzbeFpBzrFi6PJ1Kpj7Aeqf3tv45qP09UfhuP9imUzSQO0hO9Eckm5eTHUkwiuzjBJ4I6NSJoA/R2HfluQgbGox4S21wQL8Nx5MDqpevyYt4ZY+hEEgZio5Od79bQISkrzTgmfM="

    - DOCTR_VERSIONS_MENU="1"
    - DOCS_REQUIREMENTS="dev-requirements.txt"
    - PYTHON_LINT_OPTIONS="lightpath"

    - CONDA_PACKAGE="lightpath"
    - CONDA_RECIPE_FOLDER="conda-recipe"
    - CONDA_EXTRAS="pip"
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    - PIP_EXTRAS="PyQt5 -e ./"

jobs:
  allow_failures:
    - name: "Python - PIP"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda-latest.yml
