{% set data = load_setup_py_data() %}

package:
    name    : lightpath
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
       - python {{PY_VER}}*,>=3
       - setuptools

    run:
      - python {{PY_VER}}*,>=3
      - coloredlogs
      - happi >=1.6.0
      - numpy
      - ophyd
      - pcdsdevices >=3.3.0
      - prettytable
      - pydm
      - pyqt >=5
      - qtawesome
      - qtpy
      - typhos >=1.0.0

test:
    imports:
      - lightpath

about:
  home: https://github.com/pcdshub/lightpath
  license: SLAC Open License
  summary: LCLS Lightpath Module
