{% set data = load_setup_py_data() %}

package:
    name    : lightpath
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
       - python {{PY_VER}}*,>=3
       - setuptools

    run:
      - python {{PY_VER}}*,>=3
      - coloredlogs
      - happi
      - numpy
      - ophyd
      - pcdsdevices
      - prettytable
      - pydm
      - pyqt >=5 
      - qtawesome
      - qtpy
      - typhon ==0.2.1

test:
    imports:
      - lightpath

about:
  home: https://github.com/pcdshub/lightpath
  license: SLAC Open License
  summary: LCLS Lightpath Module
