{% set package_name = "lightpath" %}
{% set import_name = "lightpath" %}
{% set version =
load_file_regex(load_file=os.path.join(import_name, "_version.py"),
regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0

test:
  imports:
    - lightpath
  requires:
    - ipython
    - pytest <7.2.0
    - pytest-qt

outputs:
  - name: lightpath-base
    build:
      noarch: python
      script: python -m pip install . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools_scm
      run:
        - python >=3.6
        - coloredlogs
        - happi >=1.6.0
        - networkx <3.3
        - numpy
        - ophyd
        - prettytable

  - name: lightpath
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools_scm
      run:
        - {{ pin_subpackage('lightpath-base', max_pin='x.x') }}
        - pydm
        - pyqt >=5
        - qtawesome
        - qtpy
        - typhos >=1.0.0


about:
  home: https://github.com/pcdshub/lightpath
  license: SLAC Open License
  summary: LCLS Lightpath Module
