{% set data = load_setup_py_data() %}

package:
    name    : lightpath
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
       - python {{PY_VER}}*,>=3
       - setuptools

    run:
      - python {{PY_VER}}*,>=3
      - ophyd ==0.6.1
      - pyqt >=5 
      - numpy
      - pcaspy
      - prettytable

test:
    imports:
      - lightpath

about:
  home: https://github.com/slaclab/lightpath
  license: SLAC Open License
  summary: LCLS Lightpath Module
